# Real Estate Listing

### Application Description:

This application expose api for Real estate listing.Listing_Id is same as mls_number.

### How to Run Application Localy:

[source, bash]
----

git clone https://github.com/sonaltarpe/home-spotter-listing.git
cd home-spotter-listing
./gradlew clean build
./gradlew bootRun

----

### API's  exposed

* POST /api/v1/listings  - Create new listing  

[source, bash]
----
curl  -X POST 'http://localhost:8081/api/v1/listings' \
-H 'Content-Type: application/json' \
--data-raw '{
    "city":"Minneapolis",
    "street_address": "123 Main St",
    "agent_id":"5",
    "postal_code":"55112",
    "state":"MN",
    "asking_price":"123"

}'
----
* PUT /api/v1/listings/{listing_id} - Update existing listing

[source, bash]
----

curl --location --request PUT 'http://localhost:8081/api/v1/listings/1' \
--header 'Content-Type: application/json' \
--data-raw '{
    "listing_id": 1,
    "agent_id": 5,
    "city": "Minneapolis",
    "street_address": "123 Main St",
    "state": "MN",
    "postal_code": "55112",
    "asking_price": 123.0
}'

----
* GET /api/v1/listings/{agent_id} - Get all listing by agent_id

[source, bash]
----

curl -X GET 'http://localhost:8081/api/v1/listings?agent_id=5'

----
* Delete /api/v1/listings/{listing_id} -  Delete the listing for listing_id

[source, bash]
----

curl --location --request DELETE 'http://localhost:8081/api/v1/listings/1'

----

### Test API with Postman

* Import home-spotter.postman_collection collection file to postman
* Run application and test API's from collection

### Verify Data
* Open [http://localhost:8081/h2-console](http://localhost:8081/h2-console)
* JDBC Url: jdbc:h2:mem:listing_db
* Username: root
* Password: password


### Technologies Used

* Java with Spring Boot, and Java Validation API's Spring Data JPA
* Build Tool - Gradle
* H2 Database - In Memeory
* OS -Build with MacOSX
